# Generated by Django 3.0.10 on 2020-10-16 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scraping', '0002_auto_20201016_0748'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='city',
            options={'verbose_name': 'City name', 'verbose_name_plural': "City's name"},
        ),
    ]
